// <auto-generated />
namespace TreinamentoWeb.Infraestrutura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _001_MigrationInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_001_MigrationInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201811162005318_001_Migration Inicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
